dashboard/urls.py
from django.conf.urls import url

from . import views


app_name = 'dashboard'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # url(r'^profile/(?P<patient_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/([0-9]+)/$', views.profile, name='profile'),
    # url(r'^profile/$', views.profile, name='profile'),
    url(r'^session/$', views.session, name='session'),
    url(r'^form/$', views.form, name='form'),
    # ex: /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

rehab_platform/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	# url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls')),
]

dashboard/models.py
from __future__ import unicode_literals
import datetime
from datetime import date
from django.utils import timezone

from django.db import models
from django.utils.encoding import python_2_unicode_compatible




@python_2_unicode_compatible
class Doctor(models.Model):
    TITLE_CHOICES = (
        ('Mr', 'Mr.'),
        ('Ms', 'Ms.'),
        ('Dr', 'Dr.'),
    )

    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    
    member_since = models.DateTimeField('member since')
    title = models.CharField(max_length=2, choices=TITLE_CHOICES)

    def _get_full_name(self):
        "Returns the person's full name."
        return 'Dr. %s %s' % (self.first_name, self.last_name)

    full_name = property(_get_full_name)

    def __str__(self):
        return self.full_name
    
@python_2_unicode_compatible
class Patient(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    STATE = (
        ('Active', 'Active'),
        ('Recovered', 'Recovered'),
    )

    STATUS = (
        ('Good', 'Good'),
        ('Needs Attention', 'Needs Attention'),
        ('Check-in', 'Check-in'),
    )
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    def _get_full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.first_name, self.last_name)
    full_name = property(_get_full_name)

    DOB = models.DateField()
    def get_age(self):
        today = date.today() 
        delta = today - self.DOB
        return delta.days / 365
    age = property(get_age)

    pub_date = models.DateTimeField('date published')

    def get_last_appointment(self):
        return self.pub_date
    last_appointment = models.DateTimeField(null=True, blank=True)
    # last_appointment = property(get_last_appointment)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    rehab_focus = models.CharField(max_length=20)
    # https://github.com/stefanfoulis/django-phonenumber-field
    phone_number = models.CharField(max_length=10)
    address = models.CharField(max_length=50)
    previous_injuries = models.CharField(max_length=50)
    notes = models.CharField(max_length=200)
    recovery_percentage = models.IntegerField(default=0)
    dummy_image = models.CharField(max_length=200, default="http://pixel.nymag.com/imgs/daily/intelligencer/2015/08/10/10-donald-trump-debate.w750.h560.2x.jpg")
    next_appointment = models.DateTimeField(null=True, blank=True)
    state = models.CharField(max_length=50, default = "Active", choices=STATE)
    status = models.CharField(max_length=50, default = "Good", choices=STATUS)

    def visited_last_week(self):
        return self.last_appointment >= timezone.now() - datetime.timedelta(days=7)

    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'


    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return self.full_name


class Rehab_Session(models.Model):
    """workout session scheduled for patient to do at home"""
    patient = models.ForeignKey(Patient, blank=False, null=False, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, blank=False, null=True)

    # def get_patient_doctor(self):
    #     "Returns doctor assigned to patient"
    #     return self.patient.doctor
    # doctor = property(get_patient_doctor)

    STATUS = (
        ('Upcoming', 'Upcoming'),
        ('Missed', 'Missed'),
        ('Completed', 'Completed'),
    )

    app_date_time = models.DateTimeField(default=datetime.datetime.now())
    app_length = models.IntegerField(blank=False, null=False, default=30)
    status = models.CharField(max_length=50, default= "Upcoming", choices=STATUS)

    def get_overall_accuracy(self):
        return 99.99

    def get_overall_range_of_motion(self):
        return 79.99

    def get_exercise_categories(self):
        dic = {
            "Shoulder":35,
            "Arm": 65
        }

        return dic

    overall_accuracy = property(get_overall_accuracy)
    overall_range_of_motion = property(get_overall_range_of_motion)
    exercise_categories = property(get_exercise_categories)

    def get_appointments_for_patient(self, patient_id):
        # appointments = appointments.objects.get(patient=self.patient)
        # appointments = appointments.objects.filter(patient.id = patient_id)
        appointments = Patient.objects.get(id=patient_id).book_set.all()

    class Meta:
        verbose_name_plural = u'Appointment'

    def __str__(self):
        return u'Rehab_Session : %s for %s' % (self.id, self.patient.full_name)

class Exercise_Set(models.Model):
    """ set of excercises
        Ex. 3 sets of 15 reps of Arm Raises
    """
    rehab_session = models.ForeignKey(Rehab_Session, on_delete=models.CASCADE)
    # Exercise

    EXERCISE_CHOICES = (
    ('Arm', (
            (1, 'Forward Bicep Curl'),
            (2, 'Side Bicep Curl'),
        )
    ),
    ('Shoulder', (
            (101, 'Front Arm Raise'),
            (102, 'Lateral Arm Raise'),
        )
    ),
    ('Back', (
            (201, 'Scapular Squeeze'),
            (202, 'Thoracic Extension'),
        )
    ),
    ('Leg', (
            (301, 'Standing Hamstring Curl'),
            (302, 'Sit to Stand'),
        )
    ),
    ('Knee', (
            (401, 'Assisted Knee Flexion'),
            (402, 'Prolonged Knee Extension'),
        )
    ),

    )   

    exercise = models.CharField(max_length=200, default= 401, choices=EXERCISE_CHOICES)

    sets_total = models.IntegerField(blank=False, null=False, default=3)
    sets_completed = models.IntegerField(blank=True, null=True)
    reps_total = models.IntegerField(blank=False, null=False, default=15)
    reps_completed = models.IntegerField(blank=True, null=True)
    accuracy = models.IntegerField(blank=True, null=True)
    range_of_motion = models.IntegerField(blank=True, null=True)


    def __str__(self):
        return u'Set for %s' % (self.rehab_session)

"""
class Exercise(models.Model):
    exercise_set = models.ManyToManyField(Exercise_Set)

    EXERCISE_CATERGORIES = (
        ('Arm', 'Arm'),
        ('Shoulder', 'Shoulder'),
        ('Back', 'Back'),
        ('Leg', 'Leg'),
        ('Knee', 'Knee'),
    )

    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, choices=EXERCISE_CATERGORIES)
"""
        
    # def assign_room(self, room_id):
    #     room = Room.objects.get(id=room_id)

    #     if room.status == "Available":
    #         room.status = "Waiting"
    #         room.save()

    #         appointment = Appointment.objects.get(patient=self.patient)
    #         appointment.room = room
    #         appointment.status = "ExamRoom"
    #         appointment.save()

    # def calculate_order(self):
    #     appointments = Appointment.objects.filter(doctor=self.doctor).exclude(status="Completed", doctor_entry_time__isnull=False)
        
    #     try:
    #         max_order = Appointment.objects.get(doctor=self.doctor).exclude(status="Completed", doctor_entry_time__isnull=False).order_by('-order')
    #     except Exception, e:
    #         max_order = 0
        

    #     if not appointments:
    #         return 1
    #     else:
    #         return int(max_order) + 1

    #     return 1

    # def assign_next_patient(self):
    #     available_rooms = Room.objects.filter(status="Available")
        
    #     if available_rooms:
    #         selected_room = available_rooms[0]
    #         doctors = Doctor.objects.all()

    #         for doctor in doctors:
    #             patient_queue = Appointment.objects.filter(doctor=doctor, status="WaitingRoom").order_by('order')

    #             if patient_queue:
    #                 patient_queue[0].assign_room(selected_room.id)
    #                 return True

    #     return False

    # def save(self, *args, **kwargs):
    #     super(Appointment, self).save(*args, **kwargs)

dashboard/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from .models import Patient

import datetime
from datetime import timedelta
from django.utils.timezone import utc



# from .models import Choice, Question



def index(request):
    # upcoming_appointments = Patient.objects.get(doctor_id = "1")
    upcoming_appointments = Patient.objects.filter(state="Active").order_by('next_appointment')
    patient_list = Patient.objects.all()
    num_of_active_patients = Patient.objects.filter(state="Active").count()

    # find time until next appointment
    if len(upcoming_appointments) == 0:
        time_until_next_app = "N/A"
    else:
        next_appointment_date = upcoming_appointments[0].next_appointment
        now = datetime.datetime.utcnow().replace(tzinfo=utc)
        until_next_app = next_appointment_date - now
        if until_next_app.days > 0:
            time_until_next_app = str(until_next_app.days) + " days"
        elif (until_next_app.seconds//3600) > 0 :
            time_until_next_app = str(until_next_app.seconds//3600) + " hours"
        else:
            time_until_next_app = str((until_next_app.seconds//60)%60) + " min"

    context = {
        'time_until_next_app':time_until_next_app,
        'upcoming_appointments': upcoming_appointments,
        'patient_list': patient_list,
        'num_of_active_patients': num_of_active_patients
        }
    return render(request, 'dashboard/index.html', context)


def profile(request, patient_id):
    patient = Patient.objects.get(id = patient_id)
    recovery_percentage = patient.recovery_percentage
    if recovery_percentage < 20:
        stage1_percentage = recovery_percentage
        stage2_percentage = 0
    else:
        stage1_percentage = recovery_percentage * (0.7)
        stage2_percentage = recovery_percentage * (0.3)
    context = {
        'patient': patient,
        'stage1_percentage':stage1_percentage,
        'stage2_percentage':stage2_percentage
        }
    return render(request, 'dashboard/profile.html', context)


def session(request):
    session = "temp"
    context = {'session': session}
    return render(request, 'dashboard/session.html', context)

def form(request):
    form = "temp"
    context = {'form': form}
    return render(request, 'dashboard/form.html', context)


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

dashboard/templates/dashboard/form.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
<h3>Test</h3>
{% endblock %}

{% block content %}

    <title>AdminLTE 2 | Advanced form elements</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker-bs3.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/static/plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="/static/plugins/colorpicker/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="/static/plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/static/plugins/select2/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">

          <div class="row">

            <div class="col-md-12">




                <div class="box-header">
                  <h3 class="box-title">Make Appointment</h3>
                </div>
                <div class="box-body">
                  <!-- Date dd/mm/yyyy -->
                  <div class="form-group">
                    <label>Date:</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask>
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->


                  <!-- phone mask -->
                  <div class="form-group">
                    <label>Phone Number:</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-phone"></i>
                      </div>
                      <input type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask>
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->

                  <!-- phone mask -->
                  <div class="form-group">
                    <label>Time:</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-clock-o"></i>
                      </div>
                      <input type="text" class="form-control" data-inputmask="'mask': ['999-999-9999 [x99999]', '+099 99 99 9999[9]-9999']" data-mask>
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->

                  <a href="{% url 'dashboard:profile' %}"<button type="button" class="btn btn-primary">Submit</button></a>

                </div><!-- /.box-body -->
              </div><!-- /.box -->














            </div>

          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
      </footer>


      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>




{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
<h3>Test</h3>
{% endblock %}

{% block content %}


      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" style="min-height:100%">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
            <small>Version 2.0</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">






          <!-- top stats (cpu traffic, likes) -->
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-aqua"><i style="margin-top: 20px;" class="fa fa-users"></i></span>
                <div style="text-align:center;" class="info-box-content">
                  <span class="info-box-text" style="font-size:15px; padding-top:17px;">Total Active Patients</span>
                  <span class="info-box-number" style="font-size:25px;">{{num_of_active_patients}}<small></small></span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-red"><i style="margin-top: 20px;" class="fa fa-calendar"></i></span>
                <div style="text-align:center;" class="info-box-content">
                  <span class="info-box-text" style="font-size:15px; padding-top:17px;">Appointments this Week</span>
                  <span class="info-box-number" style="font-size:25px;">23</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix visible-sm-block"></div>

            <div class="col-md-3 col-sm-6 col-xs-12">
              <div style="text-align:center;" class="info-box">
                <span class="info-box-icon bg-green"><i style="margin-top: 20px;" class="fa fa-clock-o"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text" style="font-size:15px; padding-top:17px;">Time until next Appointment</span>
                  <span class="info-box-number" style="font-size:25px;">{{time_until_next_app}}</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div style="text-align:center;" class="info-box">
                <span class="info-box-icon bg-yellow"><i style="margin-top: 20px;" class="fa fa-smile-o"></i></span>
                <div class="info-box-content">
                  <span class="info-box-text" style="font-size:15px; padding-top:17px;">Happiness Rating</span>
                  <span class="info-box-number" style="font-size:25px;">94%</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

          <!-- Upcoming Appointment Table -->
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Upcoming Appointment</h3>
                  <div class="box-tools">
                    <div class="input-group" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Search">
                      <div class="input-group-btn">
                        <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tr>
                      <th>ID</th>
                      <th>Patient</th>
                      <th>Appointment Date</th>
                      <th>Time</th> 
                      <th>Status</th>
                      <th>Comments</th>
                    </tr>
                    {% for patient in upcoming_appointments %}                    
                      <tr>
                        <td>{{ patient.id }}</td>
                        <td><a href="{% url 'dashboard:profile' patient.id %}">{{ patient.full_name }}</a></td>
                        <!-- <td>03-01-2016</td> -->
                        <td>{{ patient.next_appointment|date:'n/j/Y' }}</td>
                        <!-- <td>12:00 PM</td> -->
                        <td>{{ patient.next_appointment|date:'P' }}</td>
                        <td><span class="label 
                          {% if patient.status == "Check-in" %} label-warning
                          {% elif patient.status == "Needs Attention" %} label-danger
                          {% else %} label-success 
                          {% endif %}

                          ">

                          {{patient.status}}</span></td>
                        <td>No comments</td>
                      </tr>
                    {% endfor %}

                  </table>



                  <!-- <table class="table table-hover">
                    <tr>
                      <th>ID</th>
                      <th>Patient</th>
                      <th>Appointment Date</th>
                      <th>Time</th> 
                      <th>Status</th>
                      <th>Comments</th>
                    </tr>
                    <tr>
                      <td>183</td>
                      <td><a href="{% url 'dashboard:profile' 1 %}">Nina Mcintiree</a></td>
                      <td>03-01-2016</td>
                      <td>12:00 PM</td>
                      <td><span class="label label-success">Good</span></td>
                      <td>No comments</td>
                    </tr>
                    <tr>
                      <td>219</td>
                      <td>Alexander Pierce</td>
                      <td>03-01-2016</td>
                      <td>12:45 PM</td>
                      <td><span class="label label-warning">Check-in</span></td>
                      <td>Serious shoulder injury.</td>
                    </tr>
                    <tr>
                      <td>657</td>
                      <td>Bob Doe</td>
                      <td>03-03-2016</td>
                      <td>2:00 PM</td>
                      <td><span class="label label-success">Good</span></td>
                      <td>Soft tissue damage in left arm</td>
                    </tr>
                    <tr>
                      <td>175</td>
                      <td>Mike Powell</td>
                      <td>03-03-2016</td>
                      <td>2:30 PM</td>
                      <td><span class="label label-success">Good</span></td>
                      <td>Lower body rehab for few months</td>
                    </tr>
                    <tr>
                      <td>273</td>
                      <td>Andrew Kang</td>
                      <td>03-03-2016</td>
                      <td>3:00 PM</td>
                      <td><span class="label label-success">Good</span></td>
                      <td>No comments</td>
                    </tr>
                    <tr>
                      <td>614</td>
                      <td>Sam Cai</td>
                      <td>03-9-2016</td>
                      <td>3:00 PM</td>
                      <td><span class="label label-danger">Needs Attention</span></td>
                      <td>Difficult to work.</td>
                    </tr>
                  </table> -->


                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>

                    <div class="row">
            <div class="col-xs-12">

              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">All Patients</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Injury Type</th>
                        <th>State</th>
                        <th>Last Visit</th>
                        <th>Age</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for patient in patient_list|dictsort:"last_name" %}                    
                      <tr>
                        <td>{{ patient.id }}</td>
                        <td><a href="{% url 'dashboard:profile' patient.id %}">{{ patient.first_name }}</a></td>
                        <td><a href="{% url 'dashboard:profile' patient.id %}">{{ patient.last_name }}</a></td>
                        <!-- <td>03-01-2016</td> -->
                        <td>{{ patient.rehab_focus }}</td>
                        <!-- <td>12:00 PM</td> -->
                        <td>{{ patient.state }}</td>
                        <td>{{patient.last_appointment|date:'n/j/Y'}}</td>
                        <!-- <td><span class="label label-success">Good</span></td> -->
                        <td>{{patient.age}}</td>
                      </tr>
                      {% endfor %}


                      <!-- <tr>
                        <td>Jake Bell</td>
                        <td>Arm</td>
                        <td>Active</td>
                        <td> 4/25/15</td>
                        <td>25</td>
                      </tr>
                      <tr>
                        <td>Sam Cai</td>
                        <td>Leg</td>
                        <td>Recovered</td>
                        <td>3/14/15</td>
                        <td>14</td>
                      </tr>
                       <tr>
                        <td>Andrew Kang</td>
                        <td>Arm</td>
                        <td>Active</td>
                        <td> 4/25/15</td>
                        <td>13</td>
                      </tr>
                       <tr>
                        <td>Pappy Smith</td>
                        <td>Shoulder</td>
                        <td>Active</td>
                        <td> 4/25/15</td>
                        <td>25</td>
                      </tr>
                       <tr>
                        <td>Hannah May</td>
                        <td>Foot</td>
                        <td>Recovered</td>
                        <td> 4/25/15</td>
                        <td>35</td>
                      </tr>
                       <tr>
                        <td>Tom Mitchell</td>
                        <td>Neck</td>
                        <td>Active</td>
                        <td> 4/25/15</td>
                        <td>42</td>
                      </tr>
                       <tr>
                        <td>Brad Smith</td>
                        <td>Arm</td>
                        <td>Active</td>
                        <td> 4/25/15</td>
                        <td>14</td>
                      </tr> -->



                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->





        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
      </footer>

      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>


          <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>




{% endblock %}